// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(EdunovaContext))]
    partial class EdunovaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Models.Djelatnik", b =>
                {
                    b.Property<int?>("Odjel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Odjel"));

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Odjel");

                    b.ToTable("Djelatnici");
                });

            modelBuilder.Entity("BackEnd.Models.Odjel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Odjeli");
                });

            modelBuilder.Entity("BackEnd.Models.Raspored", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Cetvrtak")
                        .HasColumnType("int");

                    b.Property<int?>("Nedjelja")
                        .HasColumnType("int");

                    b.Property<int?>("Petak")
                        .HasColumnType("int");

                    b.Property<int?>("Ponedjeljak")
                        .HasColumnType("int");

                    b.Property<int?>("Srijeda")
                        .HasColumnType("int");

                    b.Property<int?>("Subota")
                        .HasColumnType("int");

                    b.Property<int?>("Utorak")
                        .HasColumnType("int");

                    b.Property<int?>("djelatnik")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("djelatnik");

                    b.ToTable("Rasporedi");
                });

            modelBuilder.Entity("BackEnd.Models.Raspored", b =>
                {
                    b.HasOne("BackEnd.Models.Djelatnik", "Djelatnici")
                        .WithMany()
                        .HasForeignKey("djelatnik");

                    b.Navigation("Djelatnici");
                });
#pragma warning restore 612, 618
        }
    }
}
